export const USER_IS_LOGGING_IN = 'USER_IS_LOGGING_IN';
export const LOG_IN_SUCCESSFUL = 'LOG_IN_SUCCESSFUL';
export const LOG_IN_UNSUCCESSFUL = 'LOG_IN_UNSUCCESSFUL';

export const IS_RETRIEVING_SESSION_INFO = 'IS_RETRIEVING_SESSION_INFO';
export const RETRIEVE_SESSION_INFORMATION_SUCCESS = 'RETRIEVE_SESSION_INFORMATION_SUCCESS';
export const RETRIEVE_SESSION_INFORMATION_ERROR = 'RETRIEVE_SESSION_INFORMATION_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER'; //Persistence

export const IS_SUBMITTING = 'IS_SUBMITTING';
export const SUBMIT_SUCCESSFUL = 'SUBMIT_SUCCESSFUL';
export const SUBMIT_ERROR = 'SUBMIT_ERROR';
export const RESET_STUDENTS = 'RESET_STUDENTS';

export const RESET_SESSION = 'RESET_SESSION';
export const SET_SESSION = 'SET_SESSION';